### ISSUE TITLE
Submit/ForceSubmit failed with error "NEAR DA client invalid key length" by using golang client

### ISSUE THREAD

**Issue by wwqicode-blkchain** [near/rollup-data-availability#90]
- Darwin + golang + main branch with latest commit
- what I want to do:
  1. Get a nearDAClient
  2. Submit a string turned into bytes,
  3. get it back from da then check with the origin data.
- problem I have faced:
  I get nearDA client by `daCli, err := near.NewConfig(...)` successfully, but invoked `daCli.Submit/ForceSubmit()` failed with "NEAR DA client invalid key length: expected the input of 64 bytes, but 32 was given"
NewConfig params: 
```
const (
	DA_ACCOUNT  = "wwq.testnet"  // not the real
	DA_CONTRACT = "wwq.testnet"
	DA_KEY      = "ed25519:2b1n9bm7hLcZovzqWXCpprM2poNDQtbFEcqwWxt00000"
	DA_NETWORK  = "Testnet"
	DA_NS       = 1
)
```
the `DA_KEY` is searched by command `near` `list-keys`, is my understanding incorrect and the key value given wrong?

**Comment by wwqicode-blkchain** [comment]
I've tried to turn `DA_KEY` string into base64-string: `keyBase64 := base64.StdEncoding.EncodeToString([]byte(key))`， and treat `keyBase64` as the third parameter of NewConfig method. It throws error "NEAR DA client invalid key data: provided string contained invalid character 'O' at byte 8" when I invoke `Submit` method.

**Comment by dndll** [comment]
Hey! the key here is too small. It should be a bs58 private key, with ed25519 prefix. Here's an example:

`ed25519:3mCQyFiJ33EyVTXszgksTsSUHbKMxqsn3j9bn7PHWXQKPALadAXACLyC9R1fp9Dimax5RYw3jMxtgXp1i85V92jk`

In near-cli-rs, this is the command i used to create it.
```bash
near account create-account sponsor-by-faucet-service your-account.testnet autogenerate-new-keypair print-to-terminal network-config testnet create
```

**Comment by wwqicode-blkchain** [comment]
Thank u for your reply, and it's helpful for me. 
And I have another question while deploying contract with near-cli, can you do me a favor, thank you:
```
near contract deploy contract.testnet use-file /Users/.../rollup-data-availability/target/wasm32-unknown-unknown/release/near_da_blob_store.wasm with-init-call new json-args {} prepaid-gas '100.0 Tgas' attached-deposit '0 NEAR' network-config testnet sign-with-plaintext-private-key --signer-public-key ed25519:2b1n9bm7hLcZovzqWXCpprM2poNDQtbFEcqwWxtks5SG --signer-private-key ed25519:2MGycxC8yRuaCx3twC5FqnCgpstJmgBGq1RDkyhs44mRX2QgSwf8p6Y5HPQSV2DCSYKBFfgXSGZRwP1k3itoor96
```
I got the error msg:
```
Error:
   0: Cannot sign a transaction due to an error while fetching the most recent nonce value on network <testnet>
   1: handler error: [Access key for public key ed25519:2b1n9bm7hLcZovzqWXCpprM2poNDQtbFEcqwWxtks5SG has never been observed on the node]
```
I failed during sign tx with the key pair can be found from `.near-credentials/testnet`, and I also can't sign with keychain.
the key pair can also be found from `testnet.mynearwallet`:
![image](https://github.com/near/rollup-data-availability/assets/148736937/b3beccc5-06c5-4d56-b6f8-872f5e2b9477)

**Comment by dndll** [comment]
Hmm, this looks like the key was either:
- never created or added to the account
- removed and not removed from the local keystore
- incorrectly added

When pulling the info (assuming the legacy keychain), do you take the key from `.near-credentials/testnet/YOUR_ACCOUNT.testnet/PUBLICKEY.json`? This tends to be error prone on the user side with the legacy chain, as the legacy near cli wallet doesnt remove the inactive keys if you delete them from the account. First off, rather than --sign-with-plaintext-private-key .., sign with the legacy keychain. If that still fails you should check the legacy keychain to make sure the keys exist on the account.

If you want to get a "for sure" active key for the account, pull the keys from `.near-credentials/testnet/YOUR_ACCOUNT.json`, this is the latest key that the wallet cli knows about and how i usually check them when i get this problem.

**Comment by wwqicode-blkchain** [comment]
Everything is running well now. Thank you so much!
